package lightweight.geometry

object Constants {

  val EPSILON: Double = Double.MinPositiveValue
  val RADIANS_TURNOVER: Double = 6.28319
  val LINEAL_INTERPOLATION = 0
  val CONST_SUPPORT_TO_LEFT_POINT_INTERPOLATION = 1
  val CONST_SUPPORT_TO_RIGHT_POINT_INTERPOLATION = 2
  val CONST_SIMPLE_INTERPOLATION = 3
  val ONE_DIVIDE_ON_RADIANS_TURNOVER = 0.15915482422
}
